name: Tests

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.1, 8.0]
        laravel: [8.*, 9.*]
        dependency-version: [prefer-stable]
        include:
          - laravel: 8.*
            testbench: 6.*
          - laravel: 9.*
            testbench: ^7.0

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest
        env:
          NOVA_PASSWORD: ${{ secrets.NOVA_4_PASSWORD }}
          NOVA_USERNAME: ${{ secrets.NOVA_USERNAME }}

      - name: Execute tests
        run: vendor/bin/phpunit tests
